In [ ]:
import pandas as pd 

#Cree un DataFrame para almacenar datos meteorológicos
metereo = {'fecha' : ['12-jun-26', '13-jun-26','14-jun-26', '15-jun-26', '16-jun-26'], 
           'Grados C': [20,19,17,21,20], '%% humedad': [65, 52, 54, 84, 50],
            'condicion' : ['Soleado', 'nublado', 'lluvioso', 'soleado', 'nublado'] }
df = pd.DataFrame(metereo)

#Establezca el índice en otra columna como fechas
a = df.set_index('fecha')
print(a)

           Grados C  %% humedad condicion
fecha
12-jun-26        20          65   Soleado
13-jun-26        19          52   nublado
14-jun-26        17          54  lluvioso
15-jun-26        21          84   soleado
16-jun-26        20          50   nublado

In [27]:
#Seleccionar una fila desde el punto medio utilizando iloc
medio = len(df)//2
df.iloc[medio]

fecha         14-jun-26
Grados C             17
%% humedad           54
condicion      lluvioso
Name: 2, dtype: object

In [ ]:
#Filtre las filas que coincidan con determinados criterios numéricos con loc
grades_mask = df.loc[:,'Grados C'] <20
df[grades_mask]

       fecha  Grados C  %% humedad condicion
1  13-jun-26        19          52   nublado
2  14-jun-26        17          54  lluvioso

In [ ]:
#otra version del codigo anterior 
df.loc[df['Grados C'] > 19]

       fecha  Grados C  %% humedad condicion
0  12-jun-26        20          65   Soleado
3  15-jun-26        21          84   soleado
4  16-jun-26        20          50   nublado

In [ ]:
#Cargue un archivo CSV en un DataFrame
path = r"C:\Users\mreye\Downloads\08 - BD PERSONAS.xlsx"
pd.read_excel(path)

,COD CLIENTE,NOMBRE,APELLIDO1,APELLIDO 2,NIF,FECHA INCORPORACION
0,1968,estefania,Burgos,Ramirez,05123456c,2019-07-06
1,1674,Guillermo,Villegas,Carmona,00698741G,2021-08-21
2,1516,eliana,Fernandez,De santis,51478963T,2021-05-04
3,1330,jose,Ramirez,Franco,87456933k,2019-06-09
4,1657,marcela,Carmona,Cortes,36140394A,2019-10-08
...,...,...,...,...,...,...
109,1353,Sandra,Rodas,Jaramillo,43085815R,2019-01-10
110,1369,Evelyn,Cano,Lema,09201224W,2020-02-07
111,1370,Juan,Diaz,Caro,61772442E,2019-09-07
112,1677,David,Hernandez,Vergara,81999404Q,2019-05-29
113,1427,David,Jaramillo,Duque,34531817f,2021-05-16

In [ ]:
#Filtrar un DataFrame para mostrar sólo los valores superiores a la media
avr_grades = df['Grados C'].mean()
df.loc[df['Grados C'] > avr_grades]

       fecha  Grados C  %% humedad condicion
0  12-jun-26        20          65   Soleado
3  15-jun-26        21          84   soleado
4  16-jun-26        20          50   nublado

In [ ]:
#Combinar filtros para encontrar filas que coincidan con varias condiciones booleanas

df.loc[(df['Grados C'] > avr_grades) & (df['condicion'] == 'nublado')]

       fecha  Grados C  %% humedad condicion
4  16-jun-26        20          50   nublado

In [7]:
#Utilice isin() para filtrar datos categóricos como los tipos de producto

df.loc[df['condicion'].isin(['lluvioso', 'nublado'])]

       fecha  Grados C  %% humedad condicion
1  13-jun-26        19          52   nublado
2  14-jun-26        17          54  lluvioso
4  16-jun-26        20          50   nublado

In [ ]:
#Rebane DataFrame con .loc[] utilizando un filtro booleano

df.loc[(df['Grados C']>19), ['fecha','condicion']]

       fecha condicion
0  12-jun-26   Soleado
3  15-jun-26   soleado
4  16-jun-26   nublado

In [10]:
#Encadene filtros complejos con múltiples operadores booleanos

df.loc[(df['Grados C']>19) & ((df['condicion'] == 'lluvioso')| (df['condicion'] == 'soleado'))]

       fecha  Grados C  %% humedad condicion
3  15-jun-26        21          84   soleado

In [11]:
df.loc[(df['Grados C']>19) & (df['condicion'].isin(['lluvioso', 'soleado']))]

       fecha  Grados C  %% humedad condicion
3  15-jun-26        21          84   soleado